imports:
    - { resource: services/parameters.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Gitlabci\Command\:
        resource: '../src/Command'
        public: true
        tags: [console.command]

    Gitlabci\Output\:
        resource: '../src/Output/*'
        public: true

    Gitlabci\Factory\:
        resource: '../src/Factory/*'
        public: true

    Gitlabci\Output\OutputFormatterResolver:
        arguments:
            - ['@Gitlabci\Output\JsonOutputFormatter', '@Gitlabci\Output\YamlOutputFormatter']

    Gitlab\Client:
        factory: ['@Gitlabci\Factory\GitlabClientFactory', createGitlabClient]
        arguments: ["%gitlab.url%", "%gitlab.token%"]

